name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u 2024ab05243-git --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/2024ab05243-git/mlops-cats-dogs/cats-dogs-api:latest .

      - name: Push image
        run: docker push ghcr.io/2024ab05243-git/mlops-cats-dogs/cats-dogs-api:latest


  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Pull latest image
        run: docker compose pull

      - name: Deploy container
        run: docker compose up -d

      - name: Wait for service (Health Check)
        shell: powershell
        run: |
          for ($i = 0; $i -lt 10; $i++) {
              try {
                  $response = Invoke-WebRequest -Uri http://localhost:8000/health -UseBasicParsing
                  if ($response.StatusCode -eq 200) {
                      Write-Host "Service is up!"
                      break
                  }
              }
              catch {
                  Write-Host "Waiting for service..."
                  Start-Sleep -Seconds 5
              }
          }

      - name: Smoke Test - Prediction
        shell: powershell
        run: |
          $boundary = [System.Guid]::NewGuid().ToString()
          $filePath = "test_image.jpg"
          $fileBytes = [System.IO.File]::ReadAllBytes($filePath)

          $LF = "`r`n"
          $body = (
            "--$boundary$LF" +
            "Content-Disposition: form-data; name=`"file`"; filename=`"test_image.jpg`"$LF" +
            "Content-Type: image/jpeg$LF$LF"
          )

          $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($body)
          $endBytes = [System.Text.Encoding]::UTF8.GetBytes("$LF--$boundary--$LF")

          $requestBody = $bodyBytes + $fileBytes + $endBytes

          $response = Invoke-WebRequest `
            -Uri http://localhost:8000/predict `
            -Method Post `
            -ContentType "multipart/form-data; boundary=$boundary" `
            -Body $requestBody

          if ($response.StatusCode -ne 200) {
              Write-Host "Prediction failed"
              exit 1
          }

          Write-Host "Prediction successful"